// Auto-generated wrapper entry for difficulty
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/difficulty.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
