// Auto-generated wrapper entry for game
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/game.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
