// Auto-generated wrapper entry for home
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/home.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
